StartPage/StartPage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

StartPage/main/urls.py
from django.urls import path
from . import views

# Create your views here.
app_name = 'main'

urlpatterns = [
	path('', views.index, name = 'index'),
	path('add_fav_site', views.addFavSite, name = 'addFavSite'),
	path('<int:siteID>/del_fav_site', views.delFavSite, name = 'delFavSite'),
	path('add_news_site', views.addNewsSite, name = 'addNewsSite'),
	path('<str:siteName>/del_news_site', views.delNewsSite, name = 'delNewsSite'),
	path('update_settings', views.updateSettings, name = 'updateSettings')
]

StartPage/main/models.py
from django.db import models

class NewsSite(models.Model):
	siteName = models.CharField("Site Name", max_length=50)
	url = models.TextField("Site URL")
	nameClass = models.CharField("Name Class", max_length=50)
	nameTag = models.CharField("Name Tag", max_length=50)
	linkClass = models.CharField("Link Class", max_length=50)
	linkTag = models.CharField("Link Tag", max_length=50)
	priority = models.IntegerField("Site Priority", default=0, blank=True)

class FavSite(models.Model):
	siteName = models.CharField("Site Name", max_length=50)
	url = models.TextField("Site URL")
	img = models.TextField("Site Img", blank=True)
	priority = models.IntegerField("Site Priority", default=0, blank=True)

class Settings(models.Model):
	bgURL = models.TextField("BackGround URL", blank=True)

StartPage/main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import NewsSite, FavSite, Settings

from bs4 import BeautifulSoup
import requests as req

# Create your views here.
def index(request):
	settings = Settings.objects.get(id = 1)

	favSites = FavSite.objects.order_by("-priority")
	
	articles = NewsSite.objects.order_by("-priority")
	completeArticles = []

	for i in articles:
		a = getArticles(siteName=i.siteName, url=i.url, 
						nameClass=i.nameClass, 
						nameTag=i.nameTag, 
						linkClass=i.linkClass, 
						linkTag=i.linkTag)
		completeArticles.append(a)

	return render(request, "index.html", {'articles': completeArticles, 'favSites': favSites, 'settings': settings})

def addFavSite(request):
	fs = FavSite.objects.order_by("id")
	fs.create(siteName = request.POST.get("siteName", False), 
				url = request.POST.get("url", False), 
				img = request.POST.get("img", False), 
				priority = request.POST.get("priority", 0))
	return HttpResponseRedirect(reverse("main:index"))

def delFavSite(request, siteID):
	FavSite.objects.get(id = siteID).delete()
	return HttpResponseRedirect(reverse("main:index"))

def addNewsSite(request):
	ns = NewsSite.objects.order_by("id")
	ns.create(siteName = request.POST.get("siteName", False), 
				url = request.POST.get("url", False), 
				nameClass = request.POST.get("nameClass", False), 
				nameTag = request.POST.get("nameTag", False), 
				linkClass = request.POST.get("linkClass", False), 
				linkTag = request.POST.get("linkTag", False), 
				priority = request.POST.get("priority", 0))
	return HttpResponseRedirect(reverse("main:index"))

def delNewsSite(request, siteName):
	NewsSite.objects.get(siteName = siteName).delete()
	return HttpResponseRedirect(reverse("main:index"))

def updateSettings(request):
	settings = Settings.objects.get(id = 1)

	settings.bgURL = request.POST.get("bgURL", False)

	settings.save()

	return HttpResponseRedirect(reverse("main:index"))

def getArticles(siteName, url, nameClass, nameTag, linkClass, linkTag):
	resp = req.get(url)
	soup = BeautifulSoup(resp.text, 'lxml')

	articles = []

	articleLinks = []
	articleNames = []

	for i in soup.find_all(linkTag, class_=linkClass, href=True):
		articleLinks.append(i['href'])
	
	for i in soup.find_all(nameTag, class_=nameClass):
		articleNames.append(i.text)

	articles.append(articleLinks)
	articles.append(articleNames)
	articles.append(siteName)

	return articles

StartPage/templates/index.html
{% load index %}
{% load static %}

<!DOCTYPE html>
<html lang='en'>
	<head>
		<title>Start Page</title>

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300&display=swap" rel="stylesheet">

		<script src="https://kit.fontawesome.com/8d02cb8639.js" crossorigin="anonymous"></script>

		<link rel="stylesheet" href="static/css/style.css">
		<style type="text/css">
			body {
				background-image: url("{{ settings.bgURL }}");
			}
		</style>
	</head>
	<body>
		<main>
		<!-- \/ Settings \/ -->
			<button id="settings-button" onclick="viewSettings();"><i class="fa-solid fa-gear"></i></button>
			<div class="menu" id="settings-menu">
				<button id="fav-sites-close-button" onclick="viewSettings();"><i class="fa-solid fa-xmark"></i></button>
				<form action="{% url 'main:updateSettings' %}" method="post" autocomplete="off">
					{% csrf_token %}
					<div class="menu-form">
						<h3>Settings:</h3>
						<div class="menu-text-field">
							<label for="bgURL">BackGround image URL: </label>
							<input type="text" name="bgURL" value="">
						</div>
						<div>
							<input type="submit" value="Apply">
						</div>
					</div>
				</form>
			</div>
		<!-- /\ Settings /\ -->
		<!-- \/ Search \/ -->
			<div id="search">
				<iframe name="frame" style="display: none;"></iframe>
				<form onsubmit="search();" target="frame" autocomplete="off">
					<div id="search-text-container">
						<label for="search-text">Yandex: </label>
						<input id="search-text" name="search-text" type="text" placeholder="Write your question...">
					</div>
					<div id="search-button-container">
						<input id="search-button" type="submit" value="Search">
					</div>
				</form>
			</div>
		<!-- /\ Search /\ -->
		<!-- \/ Favorite Sites \/ -->
			<div id="fav-sites">
				<h2 id="fav-sites-text">Favorite Sites:</h2>
				<div id="fav-site-section">
				{% for i in favSites %}
					<a class="fav-site-link" href="{{ i.url }}">
						{% if i.img != "" %}
							<div class="fav-site-plate" style="background-image: url({{i.img}})">
								<form action="{% url 'main:delFavSite' siteID=i.id %}" method="post">
									{% csrf_token %}
									<button class="del-fav-site-button" type="submit"><i class="fa-solid fa-xmark"></i></button>
								</form>
							</div>
						{% else %}
							<div class="fav-site-plate no-img">
								<span>{{ i.siteName }}</span>
								<form action="{% url 'main:delFavSite' siteID=i.id %}" method="post">
									{% csrf_token %}
									<button class="del-fav-site-button" type="submit"><i class="fa-solid fa-xmark"></i></button>
								</form>
							</div>
						{% endif %}
					</a>
				{% endfor %}
				<button id="fav-sites-button" class="fav-site-plate" onclick="addFavSite();">Add Site +</button>
				</div>
			</div>
			<div class="menu" id="add-fav-sites-menu">
				<button id="fav-sites-close-button" onclick="addFavSite();"><i class="fa-solid fa-xmark"></i></button>
				<form action="{% url 'main:addFavSite' %}" method="post" autocomplete="off">
					{% csrf_token %}
					<div class="menu-form">
						<h3>Add site:</h3>
						<div class="menu-text-field">
							<label for="siteName">Site Name*: </label>
							<input type="text" name="siteName" required>
						</div>
						<div class="menu-text-field">
							<label for="url">Site URL*: </label>
							<input type="text" name="url" required>
						</div>
						<div class="menu-text-field">
							<label for="img">Site IMG: </label>
							<input type="text" name="img">
						</div>
						<div class="menu-text-field">
							<label for="priority">Site priority: </label>
							<input type="number" step="1" name="priority">
						</div>
						<div>
							<input type="submit" value="Add site">
						</div>
					</div>
				</form>
			</div>
		<!-- /\ Favorite Sites /\ -->
		<!-- \/ News \/ -->
			<div id="news">
				<h2>News:</h2>
				<div class="article-section">
					<button id="fav-sites-button" class="fav-site-plate" onclick="addNewsSite();">Add News Site +</button>
				</div>
				{% for i in articles %}
					<h3 class="site-name">{{ i|index:2 }}</h3>
					<form action="{% url 'main:delNewsSite' siteName=i|index:2 %}" method="post">
						{% csrf_token %}
						<button class="del-news-site-button" type="submit"><i class="fa-solid fa-xmark"></i></button>
					</form>
					<div class="article-section">
						{% for j in i|index:forloop.counter0|length|times %}
							<a class="article-link" href="{{ i|index:0|index:j }}">
								<div class="article-plate">
									<div>{{ i|index:1|index:j }}</div>
								</div>
							</a>
						{% endfor %}
					</div>
				{% endfor %}
			</div>
			<div class="menu" id="add-news-sites-menu">
				<button id="fav-sites-close-button" onclick="addNewsSite();"><i class="fa-solid fa-xmark"></i></button>
				<form action="{% url 'main:addNewsSite' %}" method="post" autocomplete="off">
					{% csrf_token %}
					<div class="menu-form">
						<h3>Add news site:</h3>
						<div class="menu-text-field">
							<label for="siteName">Site Name*: </label>
							<input type="text" name="siteName" required>
						</div>
						<div class="menu-text-field">
							<label for="url">Site URL*: </label>
							<input type="text" name="url" required>
						</div>
						<div class="menu-text-field">
							<label for="nameClass">Name class*: </label>
							<input type="text" name="nameClass">
						</div>
						<div class="menu-text-field">
							<label for="nameTag">Name tag*: </label>
							<input type="text" name="nameTag">
						</div>
						<div class="menu-text-field">
							<label for="linkClass">link class*: </label>
							<input type="text" name="linkClass">
						</div>
						<div class="menu-text-field">
							<label for="linkTag">link tag*: </label>
							<input type="text" name="linkTag">
						</div>
						<div class="menu-text-field">
							<label for="priority">Site priority: </label>
							<input type="number" step="1" name="priority">
						</div>
						<div>
							<input type="submit" value="Add site">
						</div>
					</div>
				</form>
			</div>
		<!-- /\ News /\ -->
			<button id="shadow-afs" onclick="addFavSite();"></button>
			<button id="shadow-ans" onclick="addNewsSite();"></button>
			<button id="shadow-s" onclick="viewSettings();"></button>
		</main>
		<script src="/static/js/script.js"></script>
	</body>
</html>